<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4a5c1f48502d97b7dbc2df045cf8803e
{
    public static $prefixLengthsPsr4 = array (
        'N' => 
        array (
            'NumberToWords\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'NumberToWords\\' => 
        array (
            0 => __DIR__ . '/..' . '/kwn/number-to-words/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4a5c1f48502d97b7dbc2df045cf8803e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4a5c1f48502d97b7dbc2df045cf8803e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4a5c1f48502d97b7dbc2df045cf8803e::$classMap;

        }, null, ClassLoader::class);
    }
}
